# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor
rand_tensor=torch.rand(7,7)

rand_tensor

tensor([[0.8961, 0.6696, 0.5120, 0.7720, 0.3804, 0.7539, 0.0986],
        [0.4520, 0.5607, 0.3000, 0.0210, 0.9646, 0.4884, 0.3228],
        [0.2247, 0.1126, 0.8479, 0.3150, 0.7711, 0.2431, 0.2098],
        [0.7697, 0.9887, 0.1596, 0.0194, 0.6899, 0.0595, 0.2755],
        [0.6576, 0.3526, 0.9994, 0.1693, 0.3682, 0.3864, 0.4914],
        [0.4827, 0.5230, 0.4859, 0.4523, 0.1197, 0.3255, 0.9032],
        [0.5909, 0.8679, 0.4731, 0.0098, 0.5459, 0.8833, 0.2260]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
rand_tensor=torch.rand(1,7)

# Perform matrix multiplication
rand_tensor*2,rand_tensor

(tensor([[1.8892, 0.0751, 1.8801, 0.0946, 0.5191, 0.5060, 1.7970]]),
 tensor([[0.9446, 0.0376, 0.9400, 0.0473, 0.2595, 0.2530, 0.8985]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [51]:
# Set manual seed
Random_seed=0
torch.manual_seed(Random_seed)

# Create two random tensors
tensorA=torch.rand(3,3)
# torch.manual_seed(Random_seed)
torch.manual_seed(Random_seed)
tensorB=torch.rand(3,3)
# Matrix multiply tensors

mul=torch.matmul(tensorA,tensorB)
tensorA,tensorB,mul

(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341],
         [0.4901, 0.8964, 0.4556]]),
 tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341],
         [0.4901, 0.8964, 0.4556]]),
 tensor([[0.3911, 0.6967, 0.5713],
         [0.4169, 0.7644, 0.4955],
         [0.5849, 1.0605, 0.8194]]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [52]:
# Set random seed on the GPU


torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [70]:
# Set random seed
Random_seed=1234
torch.manual_seed(Random_seed)
# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:{device}")
# Create two random tensors on GPU
tensorA=torch.rand(2,3).to(device)

tensorB=torch.rand(2,3).to(device)
device,tensorA,tensorB

Device:cuda


('cuda',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [72]:
# Perform matmul on tensor_A and tensor_B
c=torch.matmul(tensorA,tensorB.T)
c,c.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [74]:
# Find max
torch.min(c),torch.max(c)
# Find min


(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [77]:
# Find arg max
torch.argmin(c),torch.argmax(c)
# Find arg min


(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [78]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tens=torch.rand(1,1,1,10)

# Remove single dimensions
a=torch.squeeze(rand_tens)
# Print out tensors and their shapes
a,a.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))